{{- if .Values.pipelineConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-prepper.fullname" . }}-pipeline
  labels:
    {{- include "data-prepper.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.secretAnnotations }}
    {{- include "data-prepper.render" (dict "value" . "context" $)
        | nindent 4  }}
    {{- end }}
type: Opaque
stringData:
  pipelines.yaml: |
    {{- toYaml .Values.pipelineConfig.config | nindent 4 }}
{{- end }}
