{{- if and .Values.service.headless (ne .Values.service.type "ClusterIP") }}
{{- fail "service.headless can only be enabled when service.type is ClusterIP" }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-prepper.fullname" . }}
  labels:
    {{- include "data-prepper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- end }}
  ports:
  {{- range .Values.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
  {{- end }}
  selector:
    {{- include "data-prepper.selectorLabels" . | nindent 4 }}
