{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "opensearch.uname" . }}-config
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
data:
{{- range $configName, $configYaml := .Values.config }}
  {{- if eq $configName "log4j2.properties" }}
  {{ $configName }}: |
    {{- $configYaml | nindent 4 }}
  {{- else }}
  {{ $configName }}: |
    {{- toYaml $configYaml | nindent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
