---
{{- if .Values.maxUnavailable }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "opensearch.uname" . }}-pdb"
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "opensearch.selectorLabels" . | nindent 6 }}
{{- end }}
