apiVersion: v2
name: data-prepper
description: A Helm chart for Data Prepper

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.8.0"

maintainers:
  - name: gaiksaya
    url: https://github.com/gaiksaya
  - name: peterzhuamazon
    url: https://github.com/peterzhuamazon
  - name: prudhvigodithi
    url: https://github.com/prudhvigodithi
  - name: sergk
    url: https://github.com/sergk
  - name: TheAlgo
    url: https://github.com/TheAlgo

home: https://opensearch.org/docs/latest/data-prepper/
sources:
  - https://github.com/opensearch-project/data-prepper
  - https://github.com/opensearch-project/helm-charts

annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Data Prepper Documentation
      url: https://opensearch.org/docs/latest/data-prepper/
    - name: OpenSearch Project
      url: https://opensearch.org
